version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - '.:/app'
      - '/app/node_modules'
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile.dev
    ports:
      - 4040:4040
    volumes:
      - '.:/app'
      - '/app/node_modules'